import { Contact, Message } from "../components/ChatInterface";

export const mockContacts: Contact[] = [
  {
    id: "1",
    name: "Alice Johnson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Alice",
    lastMessage: "Hey! How are you doing?",
    timestamp: "10:30 AM",
    unreadCount: 2,
    isOnline: true,
  },
  {
    id: "2", 
    name: "Bob Smith",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Bob",
    lastMessage: "Thanks for the help yesterday 👍",
    timestamp: "9:45 AM",
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: "3",
    name: "Carol Davis",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Carol",
    lastMessage: "Let's meet for coffee tomorrow",
    timestamp: "Yesterday",
    unreadCount: 1,
    isOnline: true,
  },
  {
    id: "4",
    name: "David Wilson",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=David",
    lastMessage: "The project is looking great!",
    timestamp: "Yesterday",
    unreadCount: 0,
    isOnline: false,
  },
  {
    id: "5",
    name: "Emma Brown",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Emma",
    lastMessage: "Can you send me the files?",
    timestamp: "Monday",
    unreadCount: 3,
    isOnline: true,
  },
];

export const mockMessages: Message[] = [
  {
    id: "1",
    senderId: "1",
    text: "Hey! How are you doing?",
    timestamp: "2024-01-15T10:30:00",
    status: "delivered",
    type: "text",
  },
  {
    id: "2",
    senderId: "me",
    text: "I'm doing great, thanks for asking! How about you?",
    timestamp: "2024-01-15T10:32:00",
    status: "read",
    type: "text",
  },
  {
    id: "3",
    senderId: "1", 
    text: "Pretty good! Just working on some projects. Are you free for a call later?",
    timestamp: "2024-01-15T10:35:00",
    status: "delivered",
    type: "text",
  },
  {
    id: "4",
    senderId: "me",
    text: "Sure! I should be free around 3 PM. Does that work for you?",
    timestamp: "2024-01-15T10:37:00", 
    status: "sent",
    type: "text",
  },
  {
    id: "5",
    senderId: "1",
    text: "Perfect! I'll call you at 3 PM then. Looking forward to it 😊",
    timestamp: "2024-01-15T10:38:00",
    status: "delivered", 
    type: "text",
  },
  // Messages for Bob
  {
    id: "6",
    senderId: "2",
    text: "Thanks for the help yesterday 👍",
    timestamp: "2024-01-15T09:45:00",
    status: "read",
    type: "text",
  },
  {
    id: "7",
    senderId: "me",
    text: "No problem at all! Glad I could help.",
    timestamp: "2024-01-15T09:47:00",
    status: "read",
    type: "text",
  },
  // Messages for Carol
  {
    id: "8",
    senderId: "3",
    text: "Let's meet for coffee tomorrow",
    timestamp: "2024-01-14T16:20:00",
    status: "delivered",
    type: "text",
  },
  {
    id: "9",
    senderId: "me", 
    text: "That sounds great! What time works for you?",
    timestamp: "2024-01-14T16:22:00",
    status: "read",
    type: "text",
  },
  {
    id: "10",
    senderId: "3",
    text: "How about 10 AM at the usual place?",
    timestamp: "2024-01-14T16:25:00",
    status: "delivered",
    type: "text",
  },
];